### ISSUE TITLE
Add a verbose flag to troubleshoot HTTP exchanges

### ISSUE THREAD

**Issue by nmasse-itix** [microcks/microcks-cli#4]
When microcks-cli receives an unexpected answer from the microcks server, it can become very hard to troubleshoot the issue. 

Some of the messages I received when trying microcks-cli:
- `panic: invalid character '<' looking for beginning of value`
- `panic: interface conversion: interface {} is nil, not string`
- `panic: unexpected end of JSON input`

The error message did not help me to find the root cause of my problems (which was usually a wrong url or wrong params). I wish I could have a verbose flag that dumps HTTP exchanges. 

Maybe could we use the [DumpRequestOut](https://golang.org/pkg/net/http/httputil/#DumpRequestOut) and the [DumpResponse](https://golang.org/pkg/net/http/httputil/#DumpResponse) functions from the `net/http/httputil` package ?

**Comment by lbroudoux** [comment]
Now done @nmasse-itix ;-)
